version: '3.8'
services:
  db:
    image: postgres:14.5
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
    restart: always
  jdk:
    image: openjdk:17
